package com.realc.safe.model;

import java.io.Serializable;

public class LevelOrganization implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_level_organization.level_organization_id
     *
     * @mbg.generated
     */
    private Integer levelOrganizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_level_organization.level_organization_value
     *
     * @mbg.generated
     */
    private String levelOrganizationValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_level_organization.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table realc_level_organization
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_level_organization.level_organization_id
     *
     * @return the value of realc_level_organization.level_organization_id
     *
     * @mbg.generated
     */
    public Integer getLevelOrganizationId() {
        return levelOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_level_organization.level_organization_id
     *
     * @param levelOrganizationId the value for realc_level_organization.level_organization_id
     *
     * @mbg.generated
     */
    public void setLevelOrganizationId(Integer levelOrganizationId) {
        this.levelOrganizationId = levelOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_level_organization.level_organization_value
     *
     * @return the value of realc_level_organization.level_organization_value
     *
     * @mbg.generated
     */
    public String getLevelOrganizationValue() {
        return levelOrganizationValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_level_organization.level_organization_value
     *
     * @param levelOrganizationValue the value for realc_level_organization.level_organization_value
     *
     * @mbg.generated
     */
    public void setLevelOrganizationValue(String levelOrganizationValue) {
        this.levelOrganizationValue = levelOrganizationValue == null ? null : levelOrganizationValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_level_organization.create_time
     *
     * @return the value of realc_level_organization.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_level_organization.create_time
     *
     * @param createTime the value for realc_level_organization.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}