package com.realc.safe.model;

import java.io.Serializable;

public class LoginLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_login_log.log_id
     *
     * @mbg.generated
     */
    private String logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_login_log.log_account
     *
     * @mbg.generated
     */
    private String logAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_login_log.log_ip
     *
     * @mbg.generated
     */
    private String logIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_login_log.log_imei
     *
     * @mbg.generated
     */
    private String logImei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_login_log.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_login_log.is_success
     *
     * @mbg.generated
     */
    private String isSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table realc_login_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_login_log.log_id
     *
     * @return the value of realc_login_log.log_id
     *
     * @mbg.generated
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_login_log.log_id
     *
     * @param logId the value for realc_login_log.log_id
     *
     * @mbg.generated
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_login_log.log_account
     *
     * @return the value of realc_login_log.log_account
     *
     * @mbg.generated
     */
    public String getLogAccount() {
        return logAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_login_log.log_account
     *
     * @param logAccount the value for realc_login_log.log_account
     *
     * @mbg.generated
     */
    public void setLogAccount(String logAccount) {
        this.logAccount = logAccount == null ? null : logAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_login_log.log_ip
     *
     * @return the value of realc_login_log.log_ip
     *
     * @mbg.generated
     */
    public String getLogIp() {
        return logIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_login_log.log_ip
     *
     * @param logIp the value for realc_login_log.log_ip
     *
     * @mbg.generated
     */
    public void setLogIp(String logIp) {
        this.logIp = logIp == null ? null : logIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_login_log.log_imei
     *
     * @return the value of realc_login_log.log_imei
     *
     * @mbg.generated
     */
    public String getLogImei() {
        return logImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_login_log.log_imei
     *
     * @param logImei the value for realc_login_log.log_imei
     *
     * @mbg.generated
     */
    public void setLogImei(String logImei) {
        this.logImei = logImei == null ? null : logImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_login_log.create_time
     *
     * @return the value of realc_login_log.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_login_log.create_time
     *
     * @param createTime the value for realc_login_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_login_log.is_success
     *
     * @return the value of realc_login_log.is_success
     *
     * @mbg.generated
     */
    public String getIsSuccess() {
        return isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_login_log.is_success
     *
     * @param isSuccess the value for realc_login_log.is_success
     *
     * @mbg.generated
     */
    public void setIsSuccess(String isSuccess) {
        this.isSuccess = isSuccess == null ? null : isSuccess.trim();
    }
}