package com.realc.safe.model;

import java.io.Serializable;

public class Organization implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.organization_id
     *
     * @mbg.generated
     */
    private String organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.organization_name
     *
     * @mbg.generated
     */
    private String organizationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.is_delete
     *
     * @mbg.generated
     */
    private String isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.organization_lng
     *
     * @mbg.generated
     */
    private String organizationLng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.organization_lat
     *
     * @mbg.generated
     */
    private String organizationLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.merchant_id
     *
     * @mbg.generated
     */
    private Integer merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.organization_sort
     *
     * @mbg.generated
     */
    private Integer organizationSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.organization_open
     *
     * @mbg.generated
     */
    private String organizationOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.modify_time
     *
     * @mbg.generated
     */
    private String modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.level_organization_id
     *
     * @mbg.generated
     */
    private Integer levelOrganizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.organization_type
     *
     * @mbg.generated
     */
    private Byte organizationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.organization_owner
     *
     * @mbg.generated
     */
    private Integer organizationOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_organization.organization_roleids
     *
     * @mbg.generated
     */
    private String organizationRoleids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table realc_organization
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.organization_id
     *
     * @return the value of realc_organization.organization_id
     *
     * @mbg.generated
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.organization_id
     *
     * @param organizationId the value for realc_organization.organization_id
     *
     * @mbg.generated
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.organization_name
     *
     * @return the value of realc_organization.organization_name
     *
     * @mbg.generated
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.organization_name
     *
     * @param organizationName the value for realc_organization.organization_name
     *
     * @mbg.generated
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName == null ? null : organizationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.is_delete
     *
     * @return the value of realc_organization.is_delete
     *
     * @mbg.generated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.is_delete
     *
     * @param isDelete the value for realc_organization.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.parent_id
     *
     * @return the value of realc_organization.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.parent_id
     *
     * @param parentId the value for realc_organization.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.organization_lng
     *
     * @return the value of realc_organization.organization_lng
     *
     * @mbg.generated
     */
    public String getOrganizationLng() {
        return organizationLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.organization_lng
     *
     * @param organizationLng the value for realc_organization.organization_lng
     *
     * @mbg.generated
     */
    public void setOrganizationLng(String organizationLng) {
        this.organizationLng = organizationLng == null ? null : organizationLng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.organization_lat
     *
     * @return the value of realc_organization.organization_lat
     *
     * @mbg.generated
     */
    public String getOrganizationLat() {
        return organizationLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.organization_lat
     *
     * @param organizationLat the value for realc_organization.organization_lat
     *
     * @mbg.generated
     */
    public void setOrganizationLat(String organizationLat) {
        this.organizationLat = organizationLat == null ? null : organizationLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.merchant_id
     *
     * @return the value of realc_organization.merchant_id
     *
     * @mbg.generated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.merchant_id
     *
     * @param merchantId the value for realc_organization.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.organization_sort
     *
     * @return the value of realc_organization.organization_sort
     *
     * @mbg.generated
     */
    public Integer getOrganizationSort() {
        return organizationSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.organization_sort
     *
     * @param organizationSort the value for realc_organization.organization_sort
     *
     * @mbg.generated
     */
    public void setOrganizationSort(Integer organizationSort) {
        this.organizationSort = organizationSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.organization_open
     *
     * @return the value of realc_organization.organization_open
     *
     * @mbg.generated
     */
    public String getOrganizationOpen() {
        return organizationOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.organization_open
     *
     * @param organizationOpen the value for realc_organization.organization_open
     *
     * @mbg.generated
     */
    public void setOrganizationOpen(String organizationOpen) {
        this.organizationOpen = organizationOpen == null ? null : organizationOpen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.modify_time
     *
     * @return the value of realc_organization.modify_time
     *
     * @mbg.generated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.modify_time
     *
     * @param modifyTime the value for realc_organization.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.create_time
     *
     * @return the value of realc_organization.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.create_time
     *
     * @param createTime the value for realc_organization.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.level_organization_id
     *
     * @return the value of realc_organization.level_organization_id
     *
     * @mbg.generated
     */
    public Integer getLevelOrganizationId() {
        return levelOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.level_organization_id
     *
     * @param levelOrganizationId the value for realc_organization.level_organization_id
     *
     * @mbg.generated
     */
    public void setLevelOrganizationId(Integer levelOrganizationId) {
        this.levelOrganizationId = levelOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.organization_type
     *
     * @return the value of realc_organization.organization_type
     *
     * @mbg.generated
     */
    public Byte getOrganizationType() {
        return organizationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.organization_type
     *
     * @param organizationType the value for realc_organization.organization_type
     *
     * @mbg.generated
     */
    public void setOrganizationType(Byte organizationType) {
        this.organizationType = organizationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.organization_owner
     *
     * @return the value of realc_organization.organization_owner
     *
     * @mbg.generated
     */
    public Integer getOrganizationOwner() {
        return organizationOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.organization_owner
     *
     * @param organizationOwner the value for realc_organization.organization_owner
     *
     * @mbg.generated
     */
    public void setOrganizationOwner(Integer organizationOwner) {
        this.organizationOwner = organizationOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_organization.organization_roleids
     *
     * @return the value of realc_organization.organization_roleids
     *
     * @mbg.generated
     */
    public String getOrganizationRoleids() {
        return organizationRoleids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_organization.organization_roleids
     *
     * @param organizationRoleids the value for realc_organization.organization_roleids
     *
     * @mbg.generated
     */
    public void setOrganizationRoleids(String organizationRoleids) {
        this.organizationRoleids = organizationRoleids == null ? null : organizationRoleids.trim();
    }
}