package com.realc.safe.model;

import java.io.Serializable;

public class RoleWithBLOBs extends Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.allow_list
     *
     * @mbg.generated
     */
    private String allowList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.sendmessage_list
     *
     * @mbg.generated
     */
    private String sendmessageList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.lookprivacy_list
     *
     * @mbg.generated
     */
    private String lookprivacyList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table realc_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.allow_list
     *
     * @return the value of realc_role.allow_list
     *
     * @mbg.generated
     */
    public String getAllowList() {
        return allowList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.allow_list
     *
     * @param allowList the value for realc_role.allow_list
     *
     * @mbg.generated
     */
    public void setAllowList(String allowList) {
        this.allowList = allowList == null ? null : allowList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.sendmessage_list
     *
     * @return the value of realc_role.sendmessage_list
     *
     * @mbg.generated
     */
    public String getSendmessageList() {
        return sendmessageList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.sendmessage_list
     *
     * @param sendmessageList the value for realc_role.sendmessage_list
     *
     * @mbg.generated
     */
    public void setSendmessageList(String sendmessageList) {
        this.sendmessageList = sendmessageList == null ? null : sendmessageList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.lookprivacy_list
     *
     * @return the value of realc_role.lookprivacy_list
     *
     * @mbg.generated
     */
    public String getLookprivacyList() {
        return lookprivacyList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.lookprivacy_list
     *
     * @param lookprivacyList the value for realc_role.lookprivacy_list
     *
     * @mbg.generated
     */
    public void setLookprivacyList(String lookprivacyList) {
        this.lookprivacyList = lookprivacyList == null ? null : lookprivacyList.trim();
    }
}