package com.realc.safe.model;

import java.io.Serializable;

public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.role_status
     *
     * @mbg.generated
     */
    private String roleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.role_type
     *
     * @mbg.generated
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.role_describe
     *
     * @mbg.generated
     */
    private String roleDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.merchant_id
     *
     * @mbg.generated
     */
    private Integer merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.modify_time
     *
     * @mbg.generated
     */
    private String modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.is_allow
     *
     * @mbg.generated
     */
    private String isAllow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.is_sendmessage
     *
     * @mbg.generated
     */
    private String isSendmessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_role.is_lookprivacy
     *
     * @mbg.generated
     */
    private String isLookprivacy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table realc_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.role_id
     *
     * @return the value of realc_role.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.role_id
     *
     * @param roleId the value for realc_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.role_name
     *
     * @return the value of realc_role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.role_name
     *
     * @param roleName the value for realc_role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.role_status
     *
     * @return the value of realc_role.role_status
     *
     * @mbg.generated
     */
    public String getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.role_status
     *
     * @param roleStatus the value for realc_role.role_status
     *
     * @mbg.generated
     */
    public void setRoleStatus(String roleStatus) {
        this.roleStatus = roleStatus == null ? null : roleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.role_type
     *
     * @return the value of realc_role.role_type
     *
     * @mbg.generated
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.role_type
     *
     * @param roleType the value for realc_role.role_type
     *
     * @mbg.generated
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.create_time
     *
     * @return the value of realc_role.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.create_time
     *
     * @param createTime the value for realc_role.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.role_describe
     *
     * @return the value of realc_role.role_describe
     *
     * @mbg.generated
     */
    public String getRoleDescribe() {
        return roleDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.role_describe
     *
     * @param roleDescribe the value for realc_role.role_describe
     *
     * @mbg.generated
     */
    public void setRoleDescribe(String roleDescribe) {
        this.roleDescribe = roleDescribe == null ? null : roleDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.merchant_id
     *
     * @return the value of realc_role.merchant_id
     *
     * @mbg.generated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.merchant_id
     *
     * @param merchantId the value for realc_role.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.modify_time
     *
     * @return the value of realc_role.modify_time
     *
     * @mbg.generated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.modify_time
     *
     * @param modifyTime the value for realc_role.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.is_allow
     *
     * @return the value of realc_role.is_allow
     *
     * @mbg.generated
     */
    public String getIsAllow() {
        return isAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.is_allow
     *
     * @param isAllow the value for realc_role.is_allow
     *
     * @mbg.generated
     */
    public void setIsAllow(String isAllow) {
        this.isAllow = isAllow == null ? null : isAllow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.is_sendmessage
     *
     * @return the value of realc_role.is_sendmessage
     *
     * @mbg.generated
     */
    public String getIsSendmessage() {
        return isSendmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.is_sendmessage
     *
     * @param isSendmessage the value for realc_role.is_sendmessage
     *
     * @mbg.generated
     */
    public void setIsSendmessage(String isSendmessage) {
        this.isSendmessage = isSendmessage == null ? null : isSendmessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_role.is_lookprivacy
     *
     * @return the value of realc_role.is_lookprivacy
     *
     * @mbg.generated
     */
    public String getIsLookprivacy() {
        return isLookprivacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_role.is_lookprivacy
     *
     * @param isLookprivacy the value for realc_role.is_lookprivacy
     *
     * @mbg.generated
     */
    public void setIsLookprivacy(String isLookprivacy) {
        this.isLookprivacy = isLookprivacy == null ? null : isLookprivacy.trim();
    }
}