package com.realc.safe.model;

import java.io.Serializable;

public class SimplePassword implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_simple_password.md5
     *
     * @mbg.generated
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table realc_simple_password
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_simple_password.md5
     *
     * @return the value of realc_simple_password.md5
     *
     * @mbg.generated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_simple_password.md5
     *
     * @param md5 the value for realc_simple_password.md5
     *
     * @mbg.generated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }
}