package com.realc.safe.model;

import java.io.Serializable;

public class UserDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.is_admin
     *
     * @mbg.generated
     */
    private String isAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.merchant_id
     *
     * @mbg.generated
     */
    private Integer merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_mobile
     *
     * @mbg.generated
     */
    private String userMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_telphone
     *
     * @mbg.generated
     */
    private String userTelphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_gender
     *
     * @mbg.generated
     */
    private String userGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_email
     *
     * @mbg.generated
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.create_userid
     *
     * @mbg.generated
     */
    private Integer createUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_spell
     *
     * @mbg.generated
     */
    private String userSpell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_spell_mini
     *
     * @mbg.generated
     */
    private String userSpellMini;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.is_delete
     *
     * @mbg.generated
     */
    private String isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.source_from
     *
     * @mbg.generated
     */
    private String sourceFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.activate_state
     *
     * @mbg.generated
     */
    private String activateState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.startover_state
     *
     * @mbg.generated
     */
    private String startoverState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.sort_number
     *
     * @mbg.generated
     */
    private Integer sortNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.gesture_pwd
     *
     * @mbg.generated
     */
    private String gesturePwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.common_imei
     *
     * @mbg.generated
     */
    private String commonImei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_political
     *
     * @mbg.generated
     */
    private String userPolitical;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_weixinid
     *
     * @mbg.generated
     */
    private String userWeixinid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.gae_status
     *
     * @mbg.generated
     */
    private Byte gaeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.is_copy
     *
     * @mbg.generated
     */
    private String isCopy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.copy_merchant_id
     *
     * @mbg.generated
     */
    private Integer copyMerchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.level_id
     *
     * @mbg.generated
     */
    private String levelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.basic_data_update_time
     *
     * @mbg.generated
     */
    private Long basicDataUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.role_update_time
     *
     * @mbg.generated
     */
    private Long roleUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.im_account
     *
     * @mbg.generated
     */
    private String imAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.organization_id
     *
     * @mbg.generated
     */
    private Integer organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.user_points
     *
     * @mbg.generated
     */
    private Integer userPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realc_user_detail.im_password
     *
     * @mbg.generated
     */
    private String imPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_id
     *
     * @return the value of realc_user_detail.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_id
     *
     * @param userId the value for realc_user_detail.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.is_admin
     *
     * @return the value of realc_user_detail.is_admin
     *
     * @mbg.generated
     */
    public String getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.is_admin
     *
     * @param isAdmin the value for realc_user_detail.is_admin
     *
     * @mbg.generated
     */
    public void setIsAdmin(String isAdmin) {
        this.isAdmin = isAdmin == null ? null : isAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.merchant_id
     *
     * @return the value of realc_user_detail.merchant_id
     *
     * @mbg.generated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.merchant_id
     *
     * @param merchantId the value for realc_user_detail.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_mobile
     *
     * @return the value of realc_user_detail.user_mobile
     *
     * @mbg.generated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_mobile
     *
     * @param userMobile the value for realc_user_detail.user_mobile
     *
     * @mbg.generated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_telphone
     *
     * @return the value of realc_user_detail.user_telphone
     *
     * @mbg.generated
     */
    public String getUserTelphone() {
        return userTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_telphone
     *
     * @param userTelphone the value for realc_user_detail.user_telphone
     *
     * @mbg.generated
     */
    public void setUserTelphone(String userTelphone) {
        this.userTelphone = userTelphone == null ? null : userTelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_gender
     *
     * @return the value of realc_user_detail.user_gender
     *
     * @mbg.generated
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_gender
     *
     * @param userGender the value for realc_user_detail.user_gender
     *
     * @mbg.generated
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_email
     *
     * @return the value of realc_user_detail.user_email
     *
     * @mbg.generated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_email
     *
     * @param userEmail the value for realc_user_detail.user_email
     *
     * @mbg.generated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.create_userid
     *
     * @return the value of realc_user_detail.create_userid
     *
     * @mbg.generated
     */
    public Integer getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.create_userid
     *
     * @param createUserid the value for realc_user_detail.create_userid
     *
     * @mbg.generated
     */
    public void setCreateUserid(Integer createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_name
     *
     * @return the value of realc_user_detail.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_name
     *
     * @param userName the value for realc_user_detail.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_spell
     *
     * @return the value of realc_user_detail.user_spell
     *
     * @mbg.generated
     */
    public String getUserSpell() {
        return userSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_spell
     *
     * @param userSpell the value for realc_user_detail.user_spell
     *
     * @mbg.generated
     */
    public void setUserSpell(String userSpell) {
        this.userSpell = userSpell == null ? null : userSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_spell_mini
     *
     * @return the value of realc_user_detail.user_spell_mini
     *
     * @mbg.generated
     */
    public String getUserSpellMini() {
        return userSpellMini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_spell_mini
     *
     * @param userSpellMini the value for realc_user_detail.user_spell_mini
     *
     * @mbg.generated
     */
    public void setUserSpellMini(String userSpellMini) {
        this.userSpellMini = userSpellMini == null ? null : userSpellMini.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.is_delete
     *
     * @return the value of realc_user_detail.is_delete
     *
     * @mbg.generated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.is_delete
     *
     * @param isDelete the value for realc_user_detail.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.source_from
     *
     * @return the value of realc_user_detail.source_from
     *
     * @mbg.generated
     */
    public String getSourceFrom() {
        return sourceFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.source_from
     *
     * @param sourceFrom the value for realc_user_detail.source_from
     *
     * @mbg.generated
     */
    public void setSourceFrom(String sourceFrom) {
        this.sourceFrom = sourceFrom == null ? null : sourceFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.activate_state
     *
     * @return the value of realc_user_detail.activate_state
     *
     * @mbg.generated
     */
    public String getActivateState() {
        return activateState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.activate_state
     *
     * @param activateState the value for realc_user_detail.activate_state
     *
     * @mbg.generated
     */
    public void setActivateState(String activateState) {
        this.activateState = activateState == null ? null : activateState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.open_id
     *
     * @return the value of realc_user_detail.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.open_id
     *
     * @param openId the value for realc_user_detail.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.startover_state
     *
     * @return the value of realc_user_detail.startover_state
     *
     * @mbg.generated
     */
    public String getStartoverState() {
        return startoverState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.startover_state
     *
     * @param startoverState the value for realc_user_detail.startover_state
     *
     * @mbg.generated
     */
    public void setStartoverState(String startoverState) {
        this.startoverState = startoverState == null ? null : startoverState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.sort_number
     *
     * @return the value of realc_user_detail.sort_number
     *
     * @mbg.generated
     */
    public Integer getSortNumber() {
        return sortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.sort_number
     *
     * @param sortNumber the value for realc_user_detail.sort_number
     *
     * @mbg.generated
     */
    public void setSortNumber(Integer sortNumber) {
        this.sortNumber = sortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.gesture_pwd
     *
     * @return the value of realc_user_detail.gesture_pwd
     *
     * @mbg.generated
     */
    public String getGesturePwd() {
        return gesturePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.gesture_pwd
     *
     * @param gesturePwd the value for realc_user_detail.gesture_pwd
     *
     * @mbg.generated
     */
    public void setGesturePwd(String gesturePwd) {
        this.gesturePwd = gesturePwd == null ? null : gesturePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.create_time
     *
     * @return the value of realc_user_detail.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.create_time
     *
     * @param createTime the value for realc_user_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.common_imei
     *
     * @return the value of realc_user_detail.common_imei
     *
     * @mbg.generated
     */
    public String getCommonImei() {
        return commonImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.common_imei
     *
     * @param commonImei the value for realc_user_detail.common_imei
     *
     * @mbg.generated
     */
    public void setCommonImei(String commonImei) {
        this.commonImei = commonImei == null ? null : commonImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_political
     *
     * @return the value of realc_user_detail.user_political
     *
     * @mbg.generated
     */
    public String getUserPolitical() {
        return userPolitical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_political
     *
     * @param userPolitical the value for realc_user_detail.user_political
     *
     * @mbg.generated
     */
    public void setUserPolitical(String userPolitical) {
        this.userPolitical = userPolitical == null ? null : userPolitical.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_weixinid
     *
     * @return the value of realc_user_detail.user_weixinid
     *
     * @mbg.generated
     */
    public String getUserWeixinid() {
        return userWeixinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_weixinid
     *
     * @param userWeixinid the value for realc_user_detail.user_weixinid
     *
     * @mbg.generated
     */
    public void setUserWeixinid(String userWeixinid) {
        this.userWeixinid = userWeixinid == null ? null : userWeixinid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.gae_status
     *
     * @return the value of realc_user_detail.gae_status
     *
     * @mbg.generated
     */
    public Byte getGaeStatus() {
        return gaeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.gae_status
     *
     * @param gaeStatus the value for realc_user_detail.gae_status
     *
     * @mbg.generated
     */
    public void setGaeStatus(Byte gaeStatus) {
        this.gaeStatus = gaeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.is_copy
     *
     * @return the value of realc_user_detail.is_copy
     *
     * @mbg.generated
     */
    public String getIsCopy() {
        return isCopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.is_copy
     *
     * @param isCopy the value for realc_user_detail.is_copy
     *
     * @mbg.generated
     */
    public void setIsCopy(String isCopy) {
        this.isCopy = isCopy == null ? null : isCopy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.copy_merchant_id
     *
     * @return the value of realc_user_detail.copy_merchant_id
     *
     * @mbg.generated
     */
    public Integer getCopyMerchantId() {
        return copyMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.copy_merchant_id
     *
     * @param copyMerchantId the value for realc_user_detail.copy_merchant_id
     *
     * @mbg.generated
     */
    public void setCopyMerchantId(Integer copyMerchantId) {
        this.copyMerchantId = copyMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.level_id
     *
     * @return the value of realc_user_detail.level_id
     *
     * @mbg.generated
     */
    public String getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.level_id
     *
     * @param levelId the value for realc_user_detail.level_id
     *
     * @mbg.generated
     */
    public void setLevelId(String levelId) {
        this.levelId = levelId == null ? null : levelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.role_id
     *
     * @return the value of realc_user_detail.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.role_id
     *
     * @param roleId the value for realc_user_detail.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.basic_data_update_time
     *
     * @return the value of realc_user_detail.basic_data_update_time
     *
     * @mbg.generated
     */
    public Long getBasicDataUpdateTime() {
        return basicDataUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.basic_data_update_time
     *
     * @param basicDataUpdateTime the value for realc_user_detail.basic_data_update_time
     *
     * @mbg.generated
     */
    public void setBasicDataUpdateTime(Long basicDataUpdateTime) {
        this.basicDataUpdateTime = basicDataUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.role_update_time
     *
     * @return the value of realc_user_detail.role_update_time
     *
     * @mbg.generated
     */
    public Long getRoleUpdateTime() {
        return roleUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.role_update_time
     *
     * @param roleUpdateTime the value for realc_user_detail.role_update_time
     *
     * @mbg.generated
     */
    public void setRoleUpdateTime(Long roleUpdateTime) {
        this.roleUpdateTime = roleUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.im_account
     *
     * @return the value of realc_user_detail.im_account
     *
     * @mbg.generated
     */
    public String getImAccount() {
        return imAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.im_account
     *
     * @param imAccount the value for realc_user_detail.im_account
     *
     * @mbg.generated
     */
    public void setImAccount(String imAccount) {
        this.imAccount = imAccount == null ? null : imAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.organization_id
     *
     * @return the value of realc_user_detail.organization_id
     *
     * @mbg.generated
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.organization_id
     *
     * @param organizationId the value for realc_user_detail.organization_id
     *
     * @mbg.generated
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.user_points
     *
     * @return the value of realc_user_detail.user_points
     *
     * @mbg.generated
     */
    public Integer getUserPoints() {
        return userPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.user_points
     *
     * @param userPoints the value for realc_user_detail.user_points
     *
     * @mbg.generated
     */
    public void setUserPoints(Integer userPoints) {
        this.userPoints = userPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realc_user_detail.im_password
     *
     * @return the value of realc_user_detail.im_password
     *
     * @mbg.generated
     */
    public String getImPassword() {
        return imPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realc_user_detail.im_password
     *
     * @param imPassword the value for realc_user_detail.im_password
     *
     * @mbg.generated
     */
    public void setImPassword(String imPassword) {
        this.imPassword = imPassword == null ? null : imPassword.trim();
    }
}