package com.realc.safe.mapper;

import com.realc.safe.model.LevelUser;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface LevelUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_level_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String levelUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_level_user
     *
     * @mbg.generated
     */
    int insert(LevelUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_level_user
     *
     * @mbg.generated
     */
    int insertSelective(LevelUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_level_user
     *
     * @mbg.generated
     */
    LevelUser selectByPrimaryKey(String levelUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_level_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LevelUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_level_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LevelUser record);
}