package com.realc.safe.mapper;

import com.realc.safe.model.LoginLog;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface LoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_login_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_login_log
     *
     * @mbg.generated
     */
    int insert(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_login_log
     *
     * @mbg.generated
     */
    int insertSelective(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_login_log
     *
     * @mbg.generated
     */
    LoginLog selectByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_login_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_login_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LoginLog record);
}