package com.realc.safe.mapper;

import com.realc.safe.model.Organization;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_organization
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_organization
     *
     * @mbg.generated
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_organization
     *
     * @mbg.generated
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_organization
     *
     * @mbg.generated
     */
    Organization selectByPrimaryKey(String organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Organization record);
}