package com.realc.safe.mapper;

import com.realc.safe.model.RelationOrganizationUserdetail;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RelationOrganizationUserdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_relation_organization_userdetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_relation_organization_userdetail
     *
     * @mbg.generated
     */
    int insert(RelationOrganizationUserdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_relation_organization_userdetail
     *
     * @mbg.generated
     */
    int insertSelective(RelationOrganizationUserdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_relation_organization_userdetail
     *
     * @mbg.generated
     */
    RelationOrganizationUserdetail selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_relation_organization_userdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RelationOrganizationUserdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_relation_organization_userdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RelationOrganizationUserdetail record);
}