package com.realc.safe.mapper;

import com.realc.safe.model.Role;
import com.realc.safe.model.RoleWithBLOBs;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_role
     *
     * @mbg.generated
     */
    int insert(RoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_role
     *
     * @mbg.generated
     */
    int insertSelective(RoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_role
     *
     * @mbg.generated
     */
    RoleWithBLOBs selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(RoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Role record);
}