package com.realc.safe.mapper;

import com.realc.safe.model.SimplePassword;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SimplePasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_simple_password
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String md5);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_simple_password
     *
     * @mbg.generated
     */
    int insert(SimplePassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_simple_password
     *
     * @mbg.generated
     */
    int insertSelective(SimplePassword record);
}