package com.realc.safe.mapper;

import com.realc.safe.model.SysLog;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_sys_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_sys_log
     *
     * @mbg.generated
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_sys_log
     *
     * @mbg.generated
     */
    int insertSelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_sys_log
     *
     * @mbg.generated
     */
    SysLog selectByPrimaryKey(String sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_sys_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_sys_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_sys_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysLog record);
}