package com.realc.safe.mapper;

import com.realc.safe.model.Update;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface UpdateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_update
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String updateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_update
     *
     * @mbg.generated
     */
    int insert(Update record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_update
     *
     * @mbg.generated
     */
    int insertSelective(Update record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_update
     *
     * @mbg.generated
     */
    Update selectByPrimaryKey(String updateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_update
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Update record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_update
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Update record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_update
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Update record);
}