package com.realc.safe.mapper;

import com.realc.safe.model.UserDetail;
import org.apache.ibatis.annotations.Param;


public interface UserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    int insert(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    int insertSelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    UserDetail selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDetail record);

    /**
     * 用户登录
     * @param userName
     * @param password
     * @return
     */
    UserDetail login(@Param("user_name") String userName, @Param("password") String password);

}