package com.realc.safe.mapper;

import com.realc.safe.model.UserDetail;



public interface UserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    int insert(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    int insertSelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    UserDetail selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realc_user_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDetail record);

    /**
     * 登录
     */
    UserDetail login(String userName, String password);

}